// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwdspiyhinqkwmiwwzpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3ZHNwaXloaW5xa3dtaXd3enB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTkzOTMsImV4cCI6MjA3MTUzNTM5M30.wyjPZJ4oaTZ4BSAPevi4dihZp_Ao-FKDgRIeiuQaKEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});